- name: Ensure ansible_facts used by role
  ansible.builtin.setup:
    gather_subset: min
  when: not ansible_facts.keys() | list | intersect(__common_required_facts) == __common_required_facts
- name: Set platform/version specific variables
  ansible.builtin.include_vars: "{{ __common_vars_file }}"
  loop:
    - "{{ ansible_facts['os_family'] }}.yml"
    - "{{ ansible_facts['distribution'] }}.yml"
    - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_version'] }}.yml"
  vars:
    __common_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: __common_vars_file is file
- name: System Packages
  ansible.builtin.package:
    name: "{{ common_system_packages }}"
- name: Users
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/users.yml"
