- name: repo_apt | Include Variables
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/repo_apt.yml"
- name: repo_apt | Set dpgk_architecture fact
  ansible.builtin.set_fact:
    __common_dpkg_architecture: "{{ 'amd64' if ansible_facts['architecture'] == 'x86_64' else 'i386' }}"
    cacheable: true
- name: repo_apt | 1Password Repository
  ansible.builtin.deb822_repository:
    name: 1Password
    types: deb
    uris: "https://downloads.1password.com/linux/debian/{{ ansible_facts['__common_dpkg_architecture'] }}"
    suites: stable
    components:
      - main
    signed_by: https://downloads.1password.com/linux/keys/1password.asc
  register: __common_repo_apt_1password_repo
- name: repo_apt | Apt Update
  ansible.builtin.apt:
    update_cache: true
  when: __common_repo_apt_1password_repo.changed # noqa: no-handler
